version: '3.7'

networks:
  streamers-net:
    name: streamers-net
    driver: bridge

services:
  streamers_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "streamers_app"
    restart: unless-stopped
    expose:
      - 8000
    depends_on:
      - streamers_redis
      - streamers_db
    environment:
      - REDIS_URL="redis://user:@redis:6379/0"
      - REPO_URL="postgres://postgres:12345@streamers_db:5432/postgres?sslmode=disable"
    networks:
      - streamers-net


  streamers_redis:
    image: redis
    container_name: "streamers_redis"
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - streamers-net


  streamers_db:
    image: postgres:11.2-alpine
    container_name: "streamers_db"
    restart: unless-stopped
    volumes:
      - streamers_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=12345
    networks:
      - streamers-net


volumes:
  streamers_data:
