version: '3.7'

networks:
  monitor-net:
    name: monitor-net
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8000
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://user:@redis:6379/0
    networks:
      - monitor-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`cod-portal.ru`)
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.tls.certresolver=myresolver

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379
    labels:
      - "traefik.enable=false"
    network_mode: "host"

