version: '3.7'


services:
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379
    network_mode: "host"


  db:
    image: postgres:11.2-alpine
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=12345


volumes:
  postgres_data:
