version: '3.7'

networks:
  default:
    external:
      name: network

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8000
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://user:@redis:6379/0
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`cod-portal.ru`) # 95.217.142.210
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.tls.certresolver=myresolver

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379
    labels:
      - "traefik.enable=false"

  traefik:
    image: traefik:v2.0
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=info@cod-portal.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
